# Python Crawler 第三堂課
## 動手實作

In [1]:
import requests
from bs4 import BeautifulSoup

In [2]:
res = requests.get('https://feebee.com.tw/product/iPhone%20X%20256G%20%E6%99%BA%E6%85%A7%E5%9E%8B%E6%89%8B%E6%A9%9F/?q=iphone%20x')
soup = BeautifulSoup(res.text, 'html.parser')

In [6]:
price = []
for iPhone_price in soup.find_all(class_ = 'price ellipsis'):
    p = int(iPhone_price.text.replace(',', ''))
    price.append(p)
    print(p)

33500
33500
33500
34500
34500
34500
35275
35275
35808
35900
36026
36490
36999
36999
37477
37477
37488
37488
37488
37488

In [7]:
sum(price)/len(price)

35883.9

## 上回案例運用於不同網站演練 (六合彩)

In [2]:
url = 'http://www.lotto-8.com/listltohk.asp'
res = requests.get(url)
soup = BeautifulSoup(res.text, 'html.parser')

In [3]:
for i in soup.find_all('tr', style = 'text-align:center; background-color: #CCEEFF;'):
    text = i.text.split('\n')
    text.pop(0)
    text.pop(-1)
    text.pop(-1)
    text.pop(-1)
    text[1] = text[1].replace('\xa0','')
    print(text)
    
print('======================第一段迴圈結束======================')
    
for i2 in soup.find_all('tr', style = 'text-align:center; '):
    text = i2.text.split('\n')
    text.pop(0)
    text.pop(-1)
    text.pop(-1)
    text.pop(-1)
    text[1] = text[1].replace('\xa0','')
    print(text)

['2018/08/14', '32,37,38,42,43,49', '24']
['2018/08/09', '08,10,11,20,21,34', '13']
['2018/08/04', '04,15,23,34,37,48', '30']
['2018/07/31', '24,27,36,43,44,46', '30']
['2018/07/26', '22,32,37,44,46,49', '38']
['2018/07/21', '13,14,15,37,38,44', '40']
['2018/07/17', '06,10,32,36,41,48', '47']
['2018/07/12', '01,05,07,08,30,33', '22']
['2018/07/07', '08,17,20,26,40,46', '19']
['2018/07/03', '03,21,22,41,45,49', '10']
['2018/06/28', '06,13,23,29,38,45', '41']
['2018/06/23', '02,09,16,18,24,46', '47']
['2018/06/19', '02,07,21,31,33,42', '24']
['2018/06/14', '02,10,24,28,35,39', '27']
['2018/06/09', '11,23,35,41,46,49', '47']
['2018/06/05', '06,10,24,34,40,45', '09']
['2018/05/31', '03,05,28,33,40,49', '32']
['2018/05/26', '01,12,22,40,42,44', '28']
['2018/05/22', '07,12,14,22,31,33', '38']
['2018/05/17', '03,16,23,30,43,46', '26']
['2018/05/13', '01,06,09,19,21,23', '43']
['2018/05/08', '03,14,18,28,31,40', '38']
['2018/05/03', '12,24,30,31,32,34', '41']
['2018/04/28', '02,15,17,18,21,44', '14']
['2018/04/24', '12,20,21,28,33,41', '09']
['2018/04/19', '20,21,33,40,45,49', '43']
['2018/04/14', '12,14,15,36,38,40', '42']
['2018/04/10', '01,15,23,34,43,48', '25']
['2018/04/05', '19,24,29,39,40,42', '30']
['2018/03/31', '09,13,16,18,19,34', '21']
['2018/03/24', '12,19,23,28,35,45', '06']
['2018/03/20', '03,22,27,29,42,45', '10']
['2018/03/15', '13,16,25,35,38,49', '33']
['2018/03/10', '07,18,19,26,27,39', '02']
['2018/03/06', '02,11,17,19,35,37', '20']
['2018/03/01', '02,14,15,17,18,29', '01']
['2018/02/24', '17,20,34,38,42,45', '05']
['2018/02/20', '03,05,25,42,43,44', '02']
['2018/02/13', '02,09,18,27,32,42', '12']
['2018/02/08', '13,16,22,28,37,41', '34']
['2018/02/03', '02,04,12,25,40,49', '08']
['2018/01/30', '04,07,11,12,40,49', '25']
['2018/01/25', '03,14,23,36,40,47', '20']
['2018/01/20', '02,05,23,24,27,34', '08']
['2018/01/11', '03,29,31,43,47,49', '19']
['2018/01/02', '12,18,28,35,39,42', '36']
['2017/12/28', '15,17,23,40,44,46', '11']
['2017/12/24', '01,16,26,34,39,47', '11']
['2017/12/19', '03,09,33,38,44,49', '24']
['2017/12/14', '07,10,20,25,34,35', '08']
======================第一段迴圈結束======================
['2018/08/11', '01,11,25,38,47,49', '37']
['2018/08/07', '04,21,25,39,46,47', '12']
['2018/08/02', '03,05,11,34,35,45', '28']
['2018/07/28', '05,07,11,26,30,43', '17']
['2018/07/24', '02,16,17,27,32,37', '12']
['2018/07/19', '12,16,23,25,40,42', '20']
['2018/07/14', '07,13,22,27,33,36', '45']
['2018/07/10', '06,08,29,38,41,49', '02']
['2018/07/05', '01,13,20,34,38,40', '29']
['2018/06/30', '05,06,16,18,30,32', '27']
['2018/06/26', '07,08,12,17,33,42', '26']
['2018/06/21', '16,23,24,31,33,34', '18']
['2018/06/17', '01,07,20,21,35,48', '22']
['2018/06/12', '30,31,34,40,41,42', '33']
['2018/06/07', '05,32,34,36,38,43', '25']
['2018/06/02', '04,15,30,33,38,41', '16']
['2018/05/29', '03,06,11,22,45,46', '01']
['2018/05/24', '04,05,07,11,12,13', '18']
['2018/05/19', '14,23,29,36,37,47', '25']
['2018/05/15', '05,08,09,19,32,44', '39']
['2018/05/10', '12,19,25,31,36,49', '11']
['2018/05/05', '03,24,40,44,45,49', '08']
['2018/05/01', '01,05,10,20,21,25', '43']
['2018/04/26', '08,12,20,33,35,45', '42']
['2018/04/22', '10,14,28,30,42,44', '35']
['2018/04/17', '03,08,16,22,28,32', '24']
['2018/04/12', '01,02,09,11,37,41', '18']
['2018/04/07', '04,20,23,27,31,43', '03']
['2018/04/03', '21,29,31,41,46,49', '36']
['2018/03/29', '05,12,24,27,30,47', '43']
['2018/03/22', '10,18,21,29,33,46', '36']
['2018/03/17', '04,06,23,33,40,47', '30']
['2018/03/13', '05,16,20,25,34,42', '02']
['2018/03/08', '01,06,30,43,44,48', '07']
['2018/03/04', '06,10,11,23,28,43', '21']
['2018/02/27', '13,24,28,31,41,43', '16']
['2018/02/22', '04,12,19,20,30,39', '05']
['2018/02/15', '01,19,21,32,43,45', '34']
['2018/02/11', '01,02,09,27,33,45', '38']
['2018/02/06', '03,19,26,28,35,48', '32']
['2018/02/01', '20,23,26,29,47,49', '39']
['2018/01/27', '08,17,26,33,43,45', '40']
['2018/01/23', '03,20,27,32,37,41', '44']
['2018/01/16', '02,21,27,30,36,37', '04']
['2018/01/06', '01,12,21,31,36,49', '23']
['2017/12/30', '01,13,22,25,36,38', '37']
['2017/12/26', '02,07,16,28,30,37', '12']
['2017/12/21', '14,21,22,28,30,47', '03']
['2017/12/16', '01,03,06,09,24,28', '36']
['2017/12/12', '04,15,29,34,38,48', '30']

In [10]:
import sqlite3

conn = sqlite3.connect('/Users/myps64152002/Google 雲端硬碟/國立臺灣科技大學博士/Python 爬蟲課程/NTUST PYTHON CRAWLER/Python Crawler 3/class_data.db')
c = conn.cursor()

In [18]:
for i in soup.find_all('tr', style = 'text-align:center; background-color: #CCEEFF;'):
    text = i.text.split('\n')
    text.pop(0)
    text.pop(-1)
    text.pop(-1)
    text.pop(-1)
    text[1] = text[1].replace('\xa0','')
    num1 = text[1].split(',')[0]
    num2 = text[1].split(',')[1]
    num3 = text[1].split(',')[2]
    num4 = text[1].split(',')[3]
    num5 = text[1].split(',')[4]
    num6 = text[1].split(',')[5]
    c.execute('insert into Mark_Six(date, num1, num2, num3, num4, num5, num6, special_num) values (?, ?, ?, ?, ?, ?, ?, ?)', [text[0], num1, num2, num3, num4, num5, num6, text[2]])
    conn.commit()
    print(text[0], num1, num2, num3, num4, num5, num6, text[2])
    
for i2 in soup.find_all('tr', style = 'text-align:center; '):
    text = i2.text.split('\n')
    text.pop(0)
    text.pop(-1)
    text.pop(-1)
    text.pop(-1)
    num1 = text[1].split(',')[0]
    num2 = text[1].split(',')[1]
    num3 = text[1].split(',')[2]
    num4 = text[1].split(',')[3]
    num5 = text[1].split(',')[4]
    num6 = text[1].split(',')[5]
    c.execute('insert into Mark_Six(date, num1, num2, num3, num4, num5, num6, special_num) values (?, ?, ?, ?, ?, ?, ?, ?)', [text[0], num1, num2, num3, num4, num5, num6, text[2]])
    conn.commit()
    print(text[0], num1, num2, num3, num4, num5, num6, text[2])

2018/07/03 03 21 22 41 45 49 10
2018/06/28 06 13 23 29 38 45 41
2018/06/23 02 09 16 18 24 46 47
2018/06/19 02 07 21 31 33 42 24
2018/06/14 02 10 24 28 35 39 27
2018/06/09 11 23 35 41 46 49 47
2018/06/05 06 10 24 34 40 45 09
2018/05/31 03 05 28 33 40 49 32
2018/05/26 01 12 22 40 42 44 28
2018/05/22 07 12 14 22 31 33 38
2018/05/17 03 16 23 30 43 46 26
2018/05/13 01 06 09 19 21 23 43
2018/05/08 03 14 18 28 31 40 38
2018/05/03 12 24 30 31 32 34 41
2018/04/28 02 15 17 18 21 44 14
2018/04/24 12 20 21 28 33 41 09
2018/04/19 20 21 33 40 45 49 43
2018/04/14 12 14 15 36 38 40 42
2018/04/10 01 15 23 34 43 48 25
2018/04/05 19 24 29 39 40 42 30
2018/03/31 09 13 16 18 19 34 21
2018/03/24 12 19 23 28 35 45 06
2018/03/20 03 22 27 29 42 45 10
2018/03/15 13 16 25 35 38 49 33
2018/03/10 07 18 19 26 27 39 02
2018/03/06 02 11 17 19 35 37 20
2018/03/01 02 14 15 17 18 29 01
2018/02/24 17 20 34 38 42 45 05
2018/02/20 03 05 25 42 43 44 02
2018/02/13 02 09 18 27 32 42 12
2018/02/08 13 16 22 28 37 41 34
2018/02/03 02 04 12 25 40 49 08
2018/01/30 04 07 11 12 40 49 25
2018/01/25 03 14 23 36 40 47 20
2018/01/20 02 05 23 24 27 34 08
2018/01/11 03 29 31 43 47 49 19
2018/01/02 12 18 28 35 39 42 36
2017/12/28 15 17 23 40 44 46 11
2017/12/24 01 16 26 34 39 47 11
2017/12/19 03 09 33 38 44 49 24
2017/12/14 07 10 20 25 34 35 08
2017/12/09 22 24 29 35 38 48 30
2017/12/05 07 09 14 18 20 44 29
2017/11/30 04 10 32 35 38 47 49
2017/11/25 05 13 16 28 40 41 02
2017/11/21 08 27 30 35 36 43 31
2017/11/16 03 08 20 34 40 46 24
2017/11/12 12 16 22 28 36 37 45
2017/11/07 03 18 19 35 38 40 48
2017/11/02 05 18 20 32 36 40 07
2018/06/30 05   06   16   18   30   32 27
2018/06/26 07   08   12   17   33   42 26
2018/06/21 16   23   24   31   33   34 18
2018/06/17 01   07   20   21   35   48 22
2018/06/12 30   31   34   40   41   42 33
2018/06/07 05   32   34   36   38   43 25
2018/06/02 04   15   30   33   38   41 16
2018/05/29 03   06   11   22   45   46 01
2018/05/24 04   05   07   11   12   13 18
2018/05/19 14   23   29   36   37   47 25
2018/05/15 05   08   09   19   32   44 39
2018/05/10 12   19   25   31   36   49 11
2018/05/05 03   24   40   44   45   49 08
2018/05/01 01   05   10   20   21   25 43
2018/04/26 08   12   20   33   35   45 42
2018/04/22 10   14   28   30   42   44 35
2018/04/17 03   08   16   22   28   32 24
2018/04/12 01   02   09   11   37   41 18
2018/04/07 04   20   23   27   31   43 03
2018/04/03 21   29   31   41   46   49 36
2018/03/29 05   12   24   27   30   47 43
2018/03/22 10   18   21   29   33   46 36
2018/03/17 04   06   23   33   40   47 30
2018/03/13 05   16   20   25   34   42 02
2018/03/08 01   06   30   43   44   48 07
2018/03/04 06   10   11   23   28   43 21
2018/02/27 13   24   28   31   41   43 16
2018/02/22 04   12   19   20   30   39 05
2018/02/15 01   19   21   32   43   45 34
2018/02/11 01   02   09   27   33   45 38
2018/02/06 03   19   26   28   35   48 32
2018/02/01 20   23   26   29   47   49 39
2018/01/27 08   17   26   33   43   45 40
2018/01/23 03   20   27   32   37   41 44
2018/01/16 02   21   27   30   36   37 04
2018/01/06 01   12   21   31   36   49 23
2017/12/30 01   13   22   25   36   38 37
2017/12/26 02   07   16   28   30   37 12
2017/12/21 14   21   22   28   30   47 03
2017/12/16 01   03   06   09   24   28 36
2017/12/12 04   15   29   34   38   48 30
2017/12/07 01   25   34   37   39   47 18
2017/12/02 07   14   19   27   28   38 46
2017/11/28 06   08   09   23   36   40 19
2017/11/23 03   04   30   37   39   42 32
2017/11/18 19   24   26   30   36   41 43
2017/11/14 01   15   20   28   33   43 18
2017/11/09 03   32   36   46   48   49 29
2017/11/04 23   30   32   33   43   44 28
2017/10/31 21   26   29   35   45   49 41

## 蘋果日報實戰

In [2]:
url = 'https://tw.appledaily.com/hot/daily'

In [3]:
res = requests.get(url)
soup = BeautifulSoup(res.text, 'html.parser')

In [4]:
for i in soup.find(class_ = 'all').find_all('li'):
    num = i.find(class_ = 'aht_title_num').text
    title = i.find(class_ = 'aht_title').text
    view = i.find(class_ = 'aht_pv_num').text
    print(num, title, view)

01 獨家調查 台灣淪世界垃圾場 半年86國百萬噸湧入 121534
02 離譜 中國不要 台灣狂收 政府麻木 放任14個月 55862
03 老饕認證的好滋味　在地傳統美食飄香42年 21329
04 林瑞陽晾妻肉貼熟女 一家人數鈔真親密 29378
05 47歲鍾麗緹澄清沒發胖！女神為嫩夫拚子依舊性感！ 15324
06 2童在水上樂園遭性侵 色狼強拉被害人到漂漂河橋下逞慾 26854
07 拾荒嬤推58公斤 換回107元「快活不下去」 26247
08 街口支付涉吸金 金管會震怒 22572
09 楊靜賓館會小16歲歌手 「姊弟」按捏太激情 14644
10 扯 菲泰也把廢料丟台灣 15885
11 小戴徵男友條件 歐亞混血不說英語 13448
12 全台集氣今晚打中國 棒球 男籃齊出陣 20423
13 「要去很遠的地方」小丸子幫櫻桃子道別離 10148
14 盧廣仲 挾《花甲》11入圍光環 對幹李國毅搶視帝 16465
15 街口急了 和LINE Pay明著幹 7126
16 棄2000萬年薪 胡定吾子創街口 7495
17 聯航用貨幣區分兩岸 官網奇招抗中 我外交部：樂觀其成 17205
18 孫安佐認罪 棄上訴 12月宣判 爭取兩月內遣送回台 21655
19 足底筋膜炎治療全攻略 不再步步驚心 17060
20 獄中畫畫健身 律師：他是藝術家 16281
21 AV明日花綺羅爆G奶 附身《美女與野獸》貝兒 7839
22 《瘋狂亞洲富豪》 4帥圈粉 亨利高汀戲外台灣女婿 8594
23 晉升A咖的好機會！賓士Ａ-Class大改款８月底正式登場 11510
24 《爆炸2》12提名最威 安心亞首沾金哭了 9847
25 中國最美女總裁 李穎 一路開外掛 7742
26 搭公車頻被堵 柯改坐公務車上班 17275
27 宋慧喬 笑納 美顏零死角 雪花秀香港趴 嫻妃佘詩曼駕到 9137
28 林心如淪遺珠 誇張軒睿「好棒」 7805
29 【蘋中人】黑手變大明星 陳竹昇 12715
30 0.001秒銀恨 楊俊瀚：很嘔 14136

## 除了文字，還想將每一則的網址搜集下來怎麼做？

In [5]:
for i in soup.find(class_ = 'all').find_all('li'):
    num = i.find(class_ = 'aht_title_num').text
    title = i.find(class_ = 'aht_title').text
    view = i.find(class_ = 'aht_pv_num').text
    url =  i.find(class_ = 'aht_title').find('a').get('href')
    print(num, title, view, url)

01 獨家調查 台灣淪世界垃圾場 半年86國百萬噸湧入 121534 https://tw.news.appledaily.com/headline/daily/20180830/38112027
02 離譜 中國不要 台灣狂收 政府麻木 放任14個月 55862 https://tw.news.appledaily.com/headline/daily/20180830/38112039
03 老饕認證的好滋味　在地傳統美食飄香42年 21329 https://tw.news.appledaily.com/headline/daily/20180830/38111334
04 林瑞陽晾妻肉貼熟女 一家人數鈔真親密 29378 https://tw.entertainment.appledaily.com/daily/20180830/38111756
05 47歲鍾麗緹澄清沒發胖！女神為嫩夫拚子依舊性感！ 15324 https://tw.entertainment.appledaily.com/daily/20180830/38111379
06 2童在水上樂園遭性侵 色狼強拉被害人到漂漂河橋下逞慾 26854 https://tw.news.appledaily.com/headline/daily/20180830/38112175
07 拾荒嬤推58公斤 換回107元「快活不下去」 26247 https://tw.news.appledaily.com/headline/daily/20180830/38112056
08 街口支付涉吸金 金管會震怒 22572 https://tw.finance.appledaily.com/daily/20180830/38111607
09 楊靜賓館會小16歲歌手 「姊弟」按捏太激情 14644 https://tw.entertainment.appledaily.com/daily/20180830/38111765
10 扯 菲泰也把廢料丟台灣 15885 https://tw.news.appledaily.com/headline/daily/20180830/38112053
11 小戴徵男友條件 歐亞混血不說英語 13448 https://tw.sports.appledaily.com/daily/20180830/38111999
12 全台集氣今晚打中國 棒球 男籃齊出陣 20423 https://tw.sports.appledaily.com/daily/20180830/38111958
13 「要去很遠的地方」小丸子幫櫻桃子道別離 10148 https://tw.entertainment.appledaily.com/daily/20180830/38111785
14 盧廣仲 挾《花甲》11入圍光環 對幹李國毅搶視帝 16465 https://tw.entertainment.appledaily.com/daily/20180830/38111691
15 街口急了 和LINE Pay明著幹 7126 https://tw.finance.appledaily.com/daily/20180830/38111615
16 棄2000萬年薪 胡定吾子創街口 7495 https://tw.finance.appledaily.com/daily/20180830/38111619
17 聯航用貨幣區分兩岸 官網奇招抗中 我外交部：樂觀其成 17205 https://tw.news.appledaily.com/international/daily/20180830/38111900
18 孫安佐認罪 棄上訴 12月宣判 爭取兩月內遣送回台 21655 https://tw.news.appledaily.com/headline/daily/20180830/38112067
19 足底筋膜炎治療全攻略 不再步步驚心 17060 https://tw.news.appledaily.com/headline/daily/20180830/38110375
20 獄中畫畫健身 律師：他是藝術家 16281 https://tw.news.appledaily.com/headline/daily/20180830/38112073
21 AV明日花綺羅爆G奶 附身《美女與野獸》貝兒 7839 https://tw.entertainment.appledaily.com/daily/20180830/38111789
22 《瘋狂亞洲富豪》 4帥圈粉 亨利高汀戲外台灣女婿 8594 https://tw.entertainment.appledaily.com/daily/20180830/38111771
23 晉升A咖的好機會！賓士Ａ-Class大改款８月底正式登場 11510 https://tw.news.appledaily.com/headline/daily/20180830/38110429
24 《爆炸2》12提名最威 安心亞首沾金哭了 9847 https://tw.entertainment.appledaily.com/daily/20180830/38111705
25 中國最美女總裁 李穎 一路開外掛 7742 https://tw.finance.appledaily.com/daily/20180830/38111626
26 搭公車頻被堵 柯改坐公務車上班 17275 https://tw.news.appledaily.com/headline/daily/20180830/38111836
27 宋慧喬 笑納 美顏零死角 雪花秀香港趴 嫻妃佘詩曼駕到 9137 https://tw.entertainment.appledaily.com/daily/20180830/38111799
28 林心如淪遺珠 誇張軒睿「好棒」 7805 https://tw.entertainment.appledaily.com/daily/20180830/38111723
29 【蘋中人】黑手變大明星 陳竹昇 12715 https://tw.news.appledaily.com/headline/daily/20180830/38112091
30 0.001秒銀恨 楊俊瀚：很嘔 14136 https://tw.sports.appledaily.com/daily/20180830/38111987

## 動手實作

In [2]:
url = 'http://news.ltn.com.tw/list/newspaper'

In [3]:
res = requests.get(url)
soup = BeautifulSoup(res.text, 'html.parser')

In [4]:
for i in soup.find(class_='list').find_all('li'):
    title = i.find(class_ = 'tit').find('p').text
    tag = i.find(class_ = 'tagarea').text
    url = i.find(class_ = 'tit').get('href')
    print([title, tag, url])

['台北市長選舉 本報民調// 柯文哲33.43％丁守中24.71％姚文智14.9％', '頭版新聞', 'news/focus/paper/1228896']
['蔡政府首度執行死刑// 殘殺妻女 李宏基槍決', '頭版新聞', 'news/focus/paper/1228897']
['侵台秋颱恐一～兩個 須防共伴效應', '頭版新聞', 'news/focus/paper/1228898']
['暫聘管中閔為台大校長 法院駁回', '頭版新聞', 'news/focus/paper/1228899']
['高雄罕見日暈 揮別雨災', '頭版新聞', 'news/focus/paper/1228900']
['台北市長選舉》操盤手懸缺 柯文哲且戰且走', '焦點新聞', 'news/focus/paper/1228837']
['台北市長選舉》端政策牛肉 姚文智打團隊戰', '焦點新聞', 'news/focus/paper/1228838']
['台北市長選舉》防柯挖牆腳 丁守中勤走基層', '焦點新聞', 'news/focus/paper/1228839']
['台北市長選舉》柯文哲藍綠都吸票 姚文智衝擊較大', '焦點新聞', 'news/focus/paper/1228840']
['百里侯大戰選情評估》民進黨固守中台灣 衝雙北宜蘭', '焦點新聞', 'news/focus/paper/1228890']
['百里侯大戰選情評估》國民黨決戰中台灣 伺機奪北高', '焦點新聞', 'news/focus/paper/1228891']
['九合一大選 20993人登記', '焦點新聞', 'news/focus/paper/1228892']
['國民黨台東縣鬧分裂》鄺麗貞突登記 夫吳俊立怒嗆離婚', '焦點新聞', 'news/focus/paper/1228893']
['國民黨桃園市鬧分裂》楊麗環選定了 陳學聖斥忘恩負義', '焦點新聞', 'news/focus/paper/1228894']
['金門唯一民進黨議員陳滄江 退黨退選', '焦點新聞', 'news/focus/paper/1228895']